services:
  - type: web
    name: hsocial-app
    runtime: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
